name: Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x 
    - name: Restore the application
      run: nuget restore
    - name: Build the application
      run: dotnet publish /t:RE9SaveDecryptor /p:Configuration=Release
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: net10.0
        path: RE9SaveDecryptor/bin/Release/net10.0/publish
